raw data와 행정동별 노인인구수, 필지별 대학교 포함여부 합치기

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
%cd /content/drive/MyDrive/Project/2023/BIGCON/

/content/drive/MyDrive/Project/2023/BIGCON

In [3]:
import pandas as pd
import numpy as np

In [5]:
raw_data = pd.read_csv('데이터셋/raw_data_희중.csv', encoding = 'utf-8')
pop = pd.read_csv('행정동별_노인인구수.csv', encoding = 'cp949')
college = pd.read_csv('필지기준_대학교_포함여부.csv', encoding = 'cp949')

In [6]:
raw_data.head(2)

,DATA_CRTR_YM,LT_UNQ_NO,STDG_EMD_CD,INDUSTRY_CD,SLS_GRD,train,전체점포수,프랜차이즈점포수,일반점포수,길단위유동인구,...,폐업수,개업률,폐업률,전체 임대료,1층 임대료,1층 외 임대료,생활물가지수,부동산거래대비유동인구,공실률대비매매가임대료,젠트리피케이션
0,202201,1111010100100030100,11110101,A03,4.0,1,85.84,1.45,84.39,14929.0,...,2.03,1.189,0.696,129755.0,181103.0,78407.0,104.55,19.76,73.540769,51.190526
1,202201,1156011100104460000,11560111,A01,5.0,1,295.00,23.00,272.00,92745.0,...,7.00,3.400,2.400,93249.0,115405.0,71093.0,104.55,51.69,68.320000,43.180000

In [8]:
pop.head(2)

,DATA_CRTR_YM,LT_UNQ_NO,STDG_EMD_CD,INDUSTRY_CD,SLS_GRD,train,65세이상,65세이상_남,65세이상_여
0,202201,1111010100100030100,11110101,A03,4.0,1,2144.0,875.0,1269.0
1,202201,1156011100104460000,11560111,A01,5.0,1,3386.0,1506.0,1880.0

In [7]:
college.head(2)

,DATA_CRTR_YM,LT_UNQ_NO,STDG_EMD_CD,INDUSTRY_CD,SLS_GRD,train,college_count
0,202201,1111010100100030100,11110101,A03,4.0,1,0
1,202201,1111010100100480000,11110101,A01,2.0,1,0

In [9]:
raw_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1176040 entries, 0 to 1176039
Data columns (total 23 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   DATA_CRTR_YM  1176040 non-null  int64
 1   LT_UNQ_NO     1176040 non-null  int64
 2   STDG_EMD_CD   1176040 non-null  int64
 3   INDUSTRY_CD   1176040 non-null  object
 4   SLS_GRD       1156040 non-null  float64
 5   train         1176040 non-null  int64
 6   전체점포수         1176040 non-null  float64
 7   프랜차이즈점포수      1176040 non-null  float64
 8   일반점포수         1176040 non-null  float64
 9   길단위유동인구       1176040 non-null  float64
 10  주거인구          1176040 non-null  float64
 11  직장인구          1176040 non-null  float64
 12  개업수           1176040 non-null  float64
 13  폐업수           1176040 non-null  float64
 14  개업률           1176040 non-null  float64
 15  폐업률           1176040 non-null  float64
 16  전체 임대료        1176040 non-null  float64
 17  1층 임대료        1176040 non-null  float64
 18  1층 외 임대료      1176040 non-null  float64
 19  생활물가지수        1176040 non-null  float64
 20  부동산거래대비유동인구   1176040 non-null  float64
 21  공실률대비매매가임대료   1176040 non-null  float64
 22  젠트리피케이션       1176040 non-null  float64
dtypes: float64(18), int64(4), object(1)
memory usage: 206.4+ MB

In [11]:
pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1176040 entries, 0 to 1176039
Data columns (total 9 columns):
 #   Column        Non-Null Count    Dtype
---  ------        --------------    -----
 0   DATA_CRTR_YM  1176040 non-null  int64
 1   LT_UNQ_NO     1176040 non-null  int64
 2   STDG_EMD_CD   1176040 non-null  int64
 3   INDUSTRY_CD   1176040 non-null  object
 4   SLS_GRD       1156040 non-null  float64
 5   train         1176040 non-null  int64
 6   65세이상         1176040 non-null  float64
 7   65세이상_남       1176040 non-null  float64
 8   65세이상_여       1176040 non-null  float64
dtypes: float64(4), int64(4), object(1)
memory usage: 80.8+ MB

In [10]:
college.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1176040 entries, 0 to 1176039
Data columns (total 7 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   DATA_CRTR_YM   1176040 non-null  int64
 1   LT_UNQ_NO      1176040 non-null  int64
 2   STDG_EMD_CD    1176040 non-null  int64
 3   INDUSTRY_CD    1176040 non-null  object
 4   SLS_GRD        1156040 non-null  float64
 5   train          1176040 non-null  int64
 6   college_count  1176040 non-null  int64
dtypes: float64(1), int64(5), object(1)
memory usage: 62.8+ MB

행정동별 노인인구수 합치기

In [27]:
merge_df = pd.merge(left = raw_data, right = pop, on = ['DATA_CRTR_YM', 'LT_UNQ_NO', 'INDUSTRY_CD'], how = 'left')
merge_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1176040 entries, 0 to 1176039
Data columns (total 29 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   DATA_CRTR_YM   1176040 non-null  int64
 1   LT_UNQ_NO      1176040 non-null  int64
 2   STDG_EMD_CD_x  1176040 non-null  int64
 3   INDUSTRY_CD    1176040 non-null  object
 4   SLS_GRD_x      1156040 non-null  float64
 5   train_x        1176040 non-null  int64
 6   전체점포수          1176040 non-null  float64
 7   프랜차이즈점포수       1176040 non-null  float64
 8   일반점포수          1176040 non-null  float64
 9   길단위유동인구        1176040 non-null  float64
 10  주거인구           1176040 non-null  float64
 11  직장인구           1176040 non-null  float64
 12  개업수            1176040 non-null  float64
 13  폐업수            1176040 non-null  float64
 14  개업률            1176040 non-null  float64
 15  폐업률            1176040 non-null  float64
 16  전체 임대료         1176040 non-null  float64
 17  1층 임대료         1176040 non-null  float64
 18  1층 외 임대료       1176040 non-null  float64
 19  생활물가지수         1176040 non-null  float64
 20  부동산거래대비유동인구    1176040 non-null  float64
 21  공실률대비매매가임대료    1176040 non-null  float64
 22  젠트리피케이션        1176040 non-null  float64
 23  STDG_EMD_CD_y  1176040 non-null  int64
 24  SLS_GRD_y      1156040 non-null  float64
 25  train_y        1176040 non-null  int64
 26  65세이상          1176040 non-null  float64
 27  65세이상_남        1176040 non-null  float64
 28  65세이상_여        1176040 non-null  float64
dtypes: float64(22), int64(6), object(1)
memory usage: 269.2+ MB

필지별 대학교 포함여부 합치기

In [28]:
merge_df = pd.merge(left = merge_df, right = college, on = ['DATA_CRTR_YM', 'LT_UNQ_NO', 'INDUSTRY_CD'], how = 'left')
merge_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1176040 entries, 0 to 1176039
Data columns (total 33 columns):
 #   Column         Non-Null Count    Dtype
---  ------         --------------    -----
 0   DATA_CRTR_YM   1176040 non-null  int64
 1   LT_UNQ_NO      1176040 non-null  int64
 2   STDG_EMD_CD_x  1176040 non-null  int64
 3   INDUSTRY_CD    1176040 non-null  object
 4   SLS_GRD_x      1156040 non-null  float64
 5   train_x        1176040 non-null  int64
 6   전체점포수          1176040 non-null  float64
 7   프랜차이즈점포수       1176040 non-null  float64
 8   일반점포수          1176040 non-null  float64
 9   길단위유동인구        1176040 non-null  float64
 10  주거인구           1176040 non-null  float64
 11  직장인구           1176040 non-null  float64
 12  개업수            1176040 non-null  float64
 13  폐업수            1176040 non-null  float64
 14  개업률            1176040 non-null  float64
 15  폐업률            1176040 non-null  float64
 16  전체 임대료         1176040 non-null  float64
 17  1층 임대료         1176040 non-null  float64
 18  1층 외 임대료       1176040 non-null  float64
 19  생활물가지수         1176040 non-null  float64
 20  부동산거래대비유동인구    1176040 non-null  float64
 21  공실률대비매매가임대료    1176040 non-null  float64
 22  젠트리피케이션        1176040 non-null  float64
 23  STDG_EMD_CD_y  1176040 non-null  int64
 24  SLS_GRD_y      1156040 non-null  float64
 25  train_y        1176040 non-null  int64
 26  65세이상          1176040 non-null  float64
 27  65세이상_남        1176040 non-null  float64
 28  65세이상_여        1176040 non-null  float64
 29  STDG_EMD_CD    1176040 non-null  int64
 30  SLS_GRD        1156040 non-null  float64
 31  train          1176040 non-null  int64
 32  college_count  1176040 non-null  int64
dtypes: float64(23), int64(9), object(1)
memory usage: 305.1+ MB

In [31]:
merge_df.columns

Index(['DATA_CRTR_YM', 'LT_UNQ_NO', 'STDG_EMD_CD_x', 'INDUSTRY_CD',
       'SLS_GRD_x', 'train_x', '전체점포수', '프랜차이즈점포수', '일반점포수', '길단위유동인구', '주거인구',
       '직장인구', '개업수', '폐업수', '개업률', '폐업률', '전체 임대료', '1층 임대료', '1층 외 임대료',
       '생활물가지수', '부동산거래대비유동인구', '공실률대비매매가임대료', '젠트리피케이션', 'STDG_EMD_CD_y',
       'SLS_GRD_y', 'train_y', '65세이상', '65세이상_남', '65세이상_여', 'STDG_EMD_CD',
       'SLS_GRD', 'train', 'college_count'],
      dtype='object')

In [32]:
merge_df2 = merge_df[['DATA_CRTR_YM', 'LT_UNQ_NO', 'STDG_EMD_CD', 'INDUSTRY_CD', 'SLS_GRD', 'train',
                      '전체점포수', '프랜차이즈점포수', '일반점포수', '길단위유동인구', '주거인구', '직장인구',
                      '개업수', '폐업수', '개업률', '폐업률', '전체 임대료', '1층 임대료', '1층 외 임대료',
                      '생활물가지수', '부동산거래대비유동인구', '공실률대비매매가임대료', '젠트리피케이션',
                      '65세이상', '65세이상_남', '65세이상_여', 'college_count']]
merge_df2

,DATA_CRTR_YM,LT_UNQ_NO,STDG_EMD_CD,INDUSTRY_CD,SLS_GRD,train,전체점포수,프랜차이즈점포수,일반점포수,길단위유동인구,...,1층 임대료,1층 외 임대료,생활물가지수,부동산거래대비유동인구,공실률대비매매가임대료,젠트리피케이션,65세이상,65세이상_남,65세이상_여,college_count
0,202201,1111010100100030100,11110101,A03,4.0,1,85.840000,1.450000,84.390000,14929.000000,...,181103.000000,78407.0,104.55,19.76,73.540769,51.190526,2144.000000,875.000000,1269.000000,0
1,202201,1156011100104460000,11560111,A01,5.0,1,295.000000,23.000000,272.000000,92745.000000,...,115405.000000,71093.0,104.55,51.69,68.320000,43.180000,3386.000000,1506.000000,1880.000000,0
2,202201,1156011100104450001,11560111,A03,3.0,1,181.830000,25.230000,156.600000,92745.000000,...,115405.000000,71093.0,104.55,50.71,65.170000,45.610000,3386.000000,1506.000000,1880.000000,0
3,202201,1156011100104390000,11560111,A04,4.0,1,14.000000,3.000000,11.000000,92745.000000,...,115405.000000,71093.0,104.55,29.72,68.100000,49.390000,3386.000000,1506.000000,1880.000000,0
4,202201,1156011100104340000,11560111,A01,5.0,1,295.000000,23.000000,272.000000,92745.000000,...,115405.000000,71093.0,104.55,51.69,68.300000,46.940000,3386.000000,1506.000000,1880.000000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1176035,202302,1147010200104060293,11470102,A01,NaN,0,202.000000,37.000000,165.000000,31650.000000,...,185154.000000,99984.0,112.01,69.75,63.440000,48.680000,3537.000000,1632.000000,1905.000000,0
1176036,202302,1159010100100950000,11590101,A01,NaN,0,272.000000,23.000000,249.000000,33776.000000,...,158830.000000,131145.0,112.01,68.17,72.350000,51.210000,6007.000000,2582.000000,3425.000000,0
1176037,202302,1121510100102110002,11215101,A06,NaN,0,21.000000,5.000000,16.000000,81107.000000,...,98719.000000,95021.0,112.01,33.42,71.890000,33.150000,2957.000000,1310.000000,1647.000000,0
1176038,202302,1174010200101940007,11740102,A03,NaN,0,49.300000,13.050000,36.250000,9669.000000,...,270410.000000,148667.0,112.01,59.75,62.080000,45.270000,3189.000000,1552.000000,1637.000000,0
1176039,202302,1165010100110180001,11650101,A01,NaN,0,151.769231,14.846154,136.923077,38751.230769,...,164397.076923,130383.0,112.01,47.98,74.077744,50.004584,3618.307692,1624.076923,1994.230769,1

In [33]:
merge_df2.to_csv('데이터셋/raw_data_다경.csv', index = False, encoding = 'cp949')